export type RecordType = {
  id: string;
  RecordName: string;
  ISRCId: string;
  Singer: string;
  Composer: String;
  Producer: string;
  Genre: string;
  Format: string;
  RecordTime: string;
  dateAdd: string;
  usernameAdd: string;
  personApprove: string;
  dateApprove: string;
  RecordLink: string;
  approveStatus: boolean;
  status: boolean;
  ExpiryDate: string;
  RecordImage: string;
};
