export const FETCH_TYPE_CONTRACT_REQUEST = "FETCH_TYPE_CONTRACT_REQUEST";
export const FETCH_TYPE_CONTRACT_SUCCESS = "FETCH_TYPE_CONTRACT_SUCCESS";
export const FETCH_TYPE_CONTRACT_ERROR = "FETCH_TYPE_CONTRACT_ERROR";


export const FETCH_WARNINGWORK_REQUEST = "FETCH_WARNINGWORK_REQUEST";
export const FETCH_WARNINGWORK_SUCCESS = "FETCH_WARNINGWORK_SUCCESS";
export const FETCH_WARNINGWORK_ERROR = "FETCH_WARNINGWORK_ERROR";
