export const FETCH_TYPE_CONTRACT_REQUEST = "FETCH_TYPE_CONTRACT_REQUEST";
export const FETCH_TYPE_CONTRACT_SUCCESS = "FETCH_TYPE_CONTRACT_SUCCESS";
export const FETCH_TYPE_CONTRACT_ERROR = "FETCH_TYPE_CONTRACT_ERROR";
